# Generated by Django 2.2.28 on 2024-02-08 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20240208_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.MaxLengthValidator(128)]),
        ),
    ]
